### ISSUE TITLE
Browserify issues

### ISSUE THREAD

**Issue by inglesuniversal** [aws-samples/amazon-transcribe-websocket-static#20]
`
$ browserify main.js -o bundle.js
[BABEL] Note: The code generator has deoptimised the styling of amazon-transcribe-websocket-static/dist/main.js as it exceeds the max of 500KB.
Error: Cannot find module './audioUtils' from '/amazon-transcribe-websocket-static/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:166:21)
`

Did I do something wrong?

**Comment by inglesuniversal** [comment]
Found the problem. Was overwriting scripts.
